// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Luffy gatling 1 sprite":return img`
....................
....................
....................
....................
....................
....................
......ffffff........
.....f555555f.......
.....f222222f.......
....f25555552f......
...ffffffffffff.....
....fffdfddff.......
.....fdfddfdf.......
.....fdfddfdf.......
......fddddf........
.......ffff.........
......f2dd2f........
.....f222222f.......
....fdf2222fdf......
...fdf.f22f.fdf.....
....f..f99f..f......
.......ffff.........
.......f..f.........
.......f..f.........
.......f..f.........
......ff..ff........
....................
....................
....................
....................
`;
            case "image2":
            case "Zoro animation tori gari":return img`
....................
....................
....................
....................
....................
....................
....................
.......f6fff........
......f77777f.......
.....f7777777f......
....f777777777f.....
....f77ddddd77f.....
....f7ddfdfdd7f.....
.....fddfdfddf......
......fdddddf.......
.......fdddf........
......f7ddd7f.......
.....f77ddd77f......
....f777ddd777f.....
...fdd77ddd77ddf....
...fddf77777fddf....
....ff.f222f.ff.....
......f22222f.......
......f26666f.......
......f66666f.......
......f66666f.......
......f66f66f.......
.......ff.ff........
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
